### ISSUE TITLE
Use Payu's new ability to get executable from path loaded by environment module

### ISSUE THREAD

**Issue by dougiesquire** [ACCESS-NRI/access-om3-configs#351]
The next release of Payu (>1.1.3) will include https://github.com/payu-org/payu/pull/439. This will allow us to do something like:

```yaml
exe: access-om3-MOM6-CICE6

...

modules:
  use:
      - /g/data/ik11/spack/0.21.2/modules/access-om3/0.x.0/linux-rocky8-cascadelake
  load:
      - access-om3
```

so we won't have to update the `exe` path every time the executable is updated. We should use this.
